# Generated by Django 4.2.1 on 2023-05-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_ejecucion', models.DateField()),
                ('hora_ejecucion', models.TimeField()),
                ('repetir', models.BooleanField()),
            ],
        ),
    ]
