# Generated by Django 4.2.1 on 2023-05-06 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upv_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_reserva', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miercoles'), ('J', 'Jueves'), ('V', 'Viernes')], default='L', max_length=1)),
                ('hora_reserva', models.CharField(choices=[('0', '7:30-8:30'), ('1', '8:30-9:30'), ('2', '9:30-10:30'), ('3', '11:30-12:30'), ('4', '12:30-13:30'), ('5', '13:30-14:30'), ('6', '14:30-15:30'), ('7', '15:30-16:30'), ('8', '16:30-17:30'), ('9', '17:30-18:30'), ('10', '18:30-19:30'), ('11', '19:30-20:30'), ('12', '20:30-21:30'), ('13', '21:30-22:30')], default='0', max_length=2)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upv_bot.reserva')),
            ],
        ),
    ]
