# Generated by Django 4.2.1 on 2023-05-06 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upv_bot', '0002_horareserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='campus',
            field=models.CharField(choices=[('alcoy', 'Alcoy'), ('valencia', 'Valencia')], default='valencia', max_length=8),
        ),
        migrations.CreateModel(
            name='GymBro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('clau', models.CharField(max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
